import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      colorScheme: colorScheme,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.green900,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              5,
            ),
          ),
          shadowColor: colorScheme.primary,
          elevation: 10,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Color(0XFFFFFFFF),
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: appTheme.blue50,
              width: 1,
            ),
            borderRadius: BorderRadius.circular(
              5,
            ),
          ),
        ),
      ),
      textTheme: TextTheme(
        bodySmall: TextStyle(
          color: appTheme.blueGray300,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        labelMedium: TextStyle(
          color: appTheme.pink300,
          fontSize: getFontSize(
            10,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
      ),
      visualDensity: VisualDensity.standard,
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    background: Color(0X87223263),
    error: Color(0X87223263),
    errorContainer: Color(0X3D40BFFF),
    inversePrimary: Color(0X87223263),
    inverseSurface: Color(0X87223263),
    onBackground: Color(0X87FFFFFF),
    onError: Color(0X87FFFFFF),
    onErrorContainer: Color(0X87223263),
    onInverseSurface: Color(0X87FFFFFF),
    onPrimary: Color(0X87223263),
    onPrimaryContainer: Color(0X87FFFFFF),
    onSecondary: Color(0X87FFFFFF),
    onSecondaryContainer: Color(0X87223263),
    onSurface: Color(0X87FFFFFF),
    onSurfaceVariant: Color(0X87223263),
    onTertiary: Color(0X87FFFFFF),
    onTertiaryContainer: Color(0X87223263),
    outline: Color(0X87223263),
    outlineVariant: Color(0X87223263),
    primary: Color(0X3D40BFFF),
    primaryContainer: Color(0X87223263),
    scrim: Color(0X87223263),
    secondary: Color(0X87223263),
    secondaryContainer: Color(0X3D40BFFF),
    shadow: Color(0X87223263),
    surface: Color(0X87223263),
    surfaceTint: Color(0X87223263),
    surfaceVariant: Color(0X3D40BFFF),
    tertiary: Color(0X87223263),
    tertiaryContainer: Color(0X3D40BFFF),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber500 => Color(0XFFFFC107);
  // Black
  Color get black900 => Color(0XFF000000);
  // Blue
  Color get blue50 => Color(0XFFEAEFFF);
  Color get blueA200 => Color(0XFF4091FF);
  // BlueGray
  Color get blueGray300 => Color(0XFF9098B1);
  Color get blueGray400 => Color(0XFF888888);
  // Gray
  Color get gray400 => Color(0XFFC4C4C4);
  // Green
  Color get green900 => Color(0XFF005003);
  // Indigo
  Color get indigoA200 => Color(0XFF5B61F4);
  // Pink
  Color get pink300 => Color(0XFFFB7181);
  Color get pinkA400 => Color(0XFFFF005B);
  // Yellow
  Color get yellow700 => Color(0XFFFFC732);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
